# Site settings
title: A place to share.
description: This is my personal blog where I'll talk about Machine Learning, other cool CS stuff, philosophies and music!
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Vrishabh Lakhani
user_description: Data Science Nerd
user_title: Graduate Student pursuing Masters in Computer Science at Rochester Institute of Technology.
email: mailto:val3917@rit.edu
twitter_username: http://www.twitter.com/VrishabhLakhani
github_username:  http://www.github.com/vlraik
gplus_username:  https://www.linkedin.com/in/vrishabh-lakhani/

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
